Algoritmo "dardos"

Var


PONTO1, PONTO2, PONTO3: real
quantidade : inteiro
 


Inicio

Escreva ("primeira pontuação :" )
leia (ponto1)
 Escreva ("segunda pontuação :" )
leia (ponto2)
Escreva ("terceira pontuação :" )
leia (ponto3)

Se (ponto1 e ponto2) < ponto3 entao
escreval (" maior = ",ponto3)
Senao
Se (ponto3 e ponto2) < ponto1 entao
Escreval ("maior = ", ponto1)
Senao
 Escreval ("maior = ", ponto2)

   
   Fimse
   fimse
   


Fimalgoritmo
